create table FOOD.ADDRESS
(
  ADDRESS_ID NUMBER NOT NULL,
  STREET1 VARCHAR2(100) NOT NULL,
  STREET2 VARCHAR2(100),
  CITY VARCHAR2(100) NOT NULL,
  STATE VARCHAR2(50) NOT NULL,
  ZIP_CODE NUMBER NOT NULL
)
/
ALTER TABLE FOOD.ADDRESS
ADD CONSTRAINT ADDRESS_PK PRIMARY KEY (ADDRESS_ID)
/