create table FOOD.RESTAURANT_ITEM_XREF
(
  RESTAURANT_ID NUMBER NOT NULL,
  ITEM_ID NUMBER NOT NULL
)
/
ALTER TABLE FOOD.RESTAURANT_ITEM_XREF
ADD CONSTRAINT ITEM_XREF_REST_ID_FK FOREIGN KEY(RESTAURANT_ID)
REFERENCES FOOD.RESTAURANT(RESTAURANT_ID)
/
ALTER TABLE FOOD.RESTAURANT_ITEM_XREF
ADD CONSTRAINT REST_ITEM_XREF_ITEM_ID_FK FOREIGN KEY(ITEM_ID)
REFERENCES FOOD.ITEM(ITEM_ID)
/