create table FOOD.USERS
(
  USER_ID NUMBER NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  PHONE_NUMBER VARCHAR2(100) NOT NULL,
  ADDRESS_ID NUMBER NOT NULL,
  EMAIL VARCHAR2(100) NOT NULL
)
/
ALTER TABLE FOOD.USERS
ADD CONSTRAINT USER_PK PRIMARY KEY(USER_ID)
/
ALTER TABLE FOOD.USERS
ADD CONSTRAINT ADDRESS_ID_FK FOREIGN KEY(ADDRESS_ID)
REFERENCES FOOD.ADDRESS(ADDRESS_ID)
/
ALTER TABLE FOOD.USERS
ADD CONSTRAINT EMAIL_FK FOREIGN KEY(EMAIL)
REFERENCES FOOD.LOGIN(EMAIL)
/