create table FOOD.ORDER_ITEM_XREF
(
  ORDER_ID NUMBER NOT NULL,
  ITEM_ID NUMBER NOT NULL
)
/
ALTER TABLE FOOD.ORDER_ITEM_XREF
ADD CONSTRAINT ORDER_ITEM_XREF_ORDER_ID_FK FOREIGN KEY(ORDER_ID)
REFERENCES FOOD.ORDERS(ORDER_ID)
/
ALTER TABLE FOOD.ORDER_ITEM_XREF
ADD CONSTRAINT ORDER_ITEM_XREF_ITEM_ID_FK FOREIGN KEY(ITEM_ID)
REFERENCES FOOD.ITEM(ITEM_ID)
/