create table FOOD.ITEM
(
  ITEM_ID NUMBER NOT NULL,
  NAME VARCHAR2(250) NOT NULL,
  DESCRIPTION VARCHAR2(4000),
  PRICE NUMBER NOT NULL
)
/
ALTER TABLE FOOD.ITEM
ADD CONSTRAINT ITEM_PK PRIMARY KEY(ITEM_ID)
/