CREATE USER FOOD IDENTIFIED BY FOOD TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE TO FOOD; 
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE SYNONYM TO FOOD;

ALTER USER FOOD QUOTA UNLIMITED ON USERS;

commit;