create table FOOD.CREDITCARD
(
  NAME VARCHAR2(100) NOT NULL,
  CC_NUMBER VARCHAR2(16) NOT NULL,
  PHONE_NUMBER VARCHAR2(20) NOT NULL,
  ADDRESS_ID NUMBER NOT NULL,
  EXP_DATE DATE NOT NULL,
  USER_ID NUMBER NOT NULL,
  CC_ID NUMBER NOT NULL
)
/
ALTER TABLE FOOD.CREDITCARD
ADD CONSTRAINT CC_ADDRESS_ID_FK FOREIGN KEY(ADDRESS_ID)
REFERENCES FOOD.ADDRESS(ADDRESS_ID)
/
ALTER TABLE FOOD.CREDITCARD
ADD CONSTRAINT CC_USER_ID_FK FOREIGN KEY(USER_ID)
REFERENCES FOOD.USERS(USER_ID)
/
ALTER TABLE CREDITCARD 
ADD CONSTRAINT CC_ID_PK PRIMARY KEY(CC_ID);
/