create table FOOD.RESTAURANT
(
  RESTAURANT_ID NUMBER NOT NULL,
  NAME VARCHAR2(250) NOT NULL,
  OPEN_TIME TIMESTAMP(6) WITH TIME ZONE,
  CLOSE_TIME TIMESTAMP(6) WITH TIME ZONE,
  ADDRESS_ID NUMBER NOT NULL,
  EMAIL VARCHAR2(100) NOT NULL,
  PHONE_NUMBER VARCHAR2(100) NOT NULL
)
/
ALTER TABLE FOOD.RESTAURANT
ADD CONSTRAINT RESTAURANT_ID_PK PRIMARY KEY(RESTAURANT_ID)
/
ALTER TABLE FOOD.RESTAURANT
ADD CONSTRAINT RESTAURANT_ADDRESS_ID_FK FOREIGN KEY(ADDRESS_ID)
REFERENCES FOOD.ADDRESS(ADDRESS_ID)
/
ALTER TABLE FOOD.RESTAURANT
ADD CONSTRAINT RESTAURANT_EMAIL_FK FOREIGN KEY(EMAIL)
REFERENCES FOOD.LOGIN(EMAIL)
/