CREATE OR REPLACE TRIGGER FOOD.ADDRESS_BUIT
BEFORE INSERT OR UPDATE
ON FOOD.ADDRESS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
	IF INSERTING THEN
		IF :NEW.ADDRESS_ID IS NULL THEN
          SELECT ADDRESS_SEQ.NEXTVAL INTO :NEW.ADDRESS_ID FROM DUAL;			
    END IF;
	END IF;
END;
/
CREATE OR REPLACE TRIGGER FOOD.ITEM_BUIT
BEFORE INSERT OR UPDATE
ON FOOD.ITEM
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
	IF INSERTING THEN
		IF :NEW.ITEM_ID IS NULL THEN
          SELECT ITEM_SEQ.NEXTVAL INTO :NEW.ITEM_ID FROM DUAL;			
    END IF;
	END IF;
END;
/
CREATE OR REPLACE TRIGGER FOOD.USER_BUIT
BEFORE INSERT OR UPDATE
ON FOOD.USERS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
	IF INSERTING THEN
		IF :NEW.USER_ID IS NULL THEN
          SELECT USER_SEQ.NEXTVAL INTO :NEW.USER_ID FROM DUAL;			
    END IF;
	END IF;
END;
/
CREATE OR REPLACE TRIGGER FOOD.RESTAURANT_BUIT
BEFORE INSERT OR UPDATE
ON FOOD.RESTAURANT
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
	IF INSERTING THEN
		IF :NEW.RESTAURANT_ID IS NULL THEN
          SELECT RESTAURANT_SEQ.NEXTVAL INTO :NEW.RESTAURANT_ID FROM DUAL;			
    END IF;
	END IF;
END;
/
CREATE OR REPLACE TRIGGER FOOD.ORDER_BUIT
BEFORE INSERT OR UPDATE
ON FOOD.ORDERS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
	IF INSERTING THEN
    :NEW.RCRD_CRTD_DT := SYSTIMESTAMP;
		IF :NEW.ORDER_ID IS NULL THEN
          SELECT ORDER_SEQ.NEXTVAL INTO :NEW.ORDER_ID FROM DUAL;			
    END IF;
	END IF;
END;
/
CREATE OR REPLACE TRIGGER FOOD.CREDITCARD_BUIT
BEFORE INSERT OR UPDATE
ON FOOD.CREDITCARD
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
	IF INSERTING THEN
		IF :NEW.CC_ID IS NULL THEN
          SELECT CC_ID_SEQ.NEXTVAL INTO :NEW.CC_ID FROM DUAL;			
    END IF;
	END IF;
END;
/